const String kJob = "Job";
const String know = "Now";
const String kNext = "Next";
const String kBack = "Back";
const String ksignInUP = "Sign In/Up";
const String kLinkedIn = "Connect With LinkedIn ";
const String kFindJob = "Find job offers from the most popular job listing sites ";
const String kTrackJobText = "Track all your job applicatons and don’t get lost in the process ";
const String kStartApp = "Start appliying and get a Job Now!";
